// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qupnktmlaskiassawrja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1cG5rdG1sYXNraWFzc2F3cmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTA0ODYsImV4cCI6MjA2NzQ2NjQ4Nn0.2CbV15_SpO3GHjcwchrZdm2OvfJ1_yh1lp0hBPy1Oq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});